plugins { id 'com.android.application' }
android {
  namespace 'org.safesep.consumer'
  compileSdk 35
  defaultConfig {
    applicationId 'org.safesep.consumer'
    minSdk 33
    targetSdk 35
    versionCode 1
    versionName '0.1'
    testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
  }
}
dependencies {
  androidTestImplementation 'androidx.test:runner:1.6.2'
  androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
